language: c

compiler: gcc

#install: make - test commit
script: 
 - gcc ctest.c -o cout
 - PLATFORM=$(uname -m)
 - if [ "${PLATFORM}" = 'ppc64' -o "${PLATFORM}" = 'ppc64le' ]; then echo "Its ppc hardware"; fi
